# Generated by Django 4.2 on 2023-04-28 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pvapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_image', models.ImageField(null=True, upload_to='album_img/')),
                ('title', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(default='', upload_to='Video/%y', validators=[pvapp.validators.file_size])),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pvapp.album')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('alt_text', models.CharField(max_length=100)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pvapp.album')),
            ],
        ),
    ]
