# Generated by Django 4.2 on 2023-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvapp', '0003_remove_album_status_album_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
