# Generated by Django 4.2 on 2023-04-29 13:20

from django.db import migrations, models
import pvapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pvapp', '0005_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='Video/%y', validators=[pvapp.validators.file_size]),
        ),
    ]
