# Generated by Django 4.2 on 2023-04-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvapp', '0006_alter_video_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotosVideo',
            new_name='Photo',
        ),
    ]
